//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell_WebP_Converter.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "18.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shell_WebP_Converter.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add a conversion menu entry for folders.
        /// </summary>
        public static string AddConversionEntryForFolders {
            get {
                return ResourceManager.GetString("AddConversionEntryForFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Add an option to convert WebP files to PNG/JPG.
        /// </summary>
        public static string AddOptionToConvertToJPG_PNG {
            get {
                return ResourceManager.GetString("AddOptionToConvertToJPG_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Advanced mode.
        /// </summary>
        public static string AdvancedMode {
            get {
                return ResourceManager.GetString("AdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Any ➔ WebP.
        /// </summary>
        public static string AnyToWebp {
            get {
                return ResourceManager.GetString("AnyToWebp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Clear context menu.
        /// </summary>
        public static string ClearContextMenu {
            get {
                return ResourceManager.GetString("ClearContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Path to the input file.
        /// </summary>
        public static string CLI_InputTooltip {
            get {
                return ResourceManager.GetString("CLI_InputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compression level:.
        /// </summary>
        public static string CompressionLevelColon {
            get {
                return ResourceManager.GetString("CompressionLevelColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compression, from 0 to 9, a higher value leads to reduced size and slower conversion speed..
        /// </summary>
        public static string CompressionTooltipForPNG {
            get {
                return ResourceManager.GetString("CompressionTooltipForPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compression, from 0 to 6, a higher value leads to a reduction in size or an increase in quality at the same size, also leads to a decrease in the conversion rate.
        /// </summary>
        public static string CompressionTooltipForWebP {
            get {
                return ResourceManager.GetString("CompressionTooltipForWebP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compress to.
        /// </summary>
        public static string CompressTo {
            get {
                return ResourceManager.GetString("CompressTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Compress to a specific file size.
        /// </summary>
        public static string CompressToThreshold {
            get {
                return ResourceManager.GetString("CompressToThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на One or more conversion failed. See logs for details.
        /// </summary>
        public static string ConversionFail {
            get {
                return ResourceManager.GetString("ConversionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to JPG/PNG.
        /// </summary>
        public static string ConvertToJPG_PNG {
            get {
                return ResourceManager.GetString("ConvertToJPG_PNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convert to WebP.
        /// </summary>
        public static string ConvertToWebP {
            get {
                return ResourceManager.GetString("ConvertToWebP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom conversion settings.
        /// </summary>
        public static string CustomConversionSettings {
            get {
                return ResourceManager.GetString("CustomConversionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customizable.
        /// </summary>
        public static string Customizable {
            get {
                return ResourceManager.GetString("Customizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на There can be only one preset with the &quot;customizable&quot; mode in the set.
        /// </summary>
        public static string CustomizableAlreadyExists {
            get {
                return ResourceManager.GetString("CustomizableAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Customizable quality.
        /// </summary>
        public static string CustomizableQuality {
            get {
                return ResourceManager.GetString("CustomizableQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Custom settings .
        /// </summary>
        public static string CustomSettings {
            get {
                return ResourceManager.GetString("CustomSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete original.
        /// </summary>
        public static string DeleteOriginal {
            get {
                return ResourceManager.GetString("DeleteOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Delete original file.
        /// </summary>
        public static string DeleteOriginalFile {
            get {
                return ResourceManager.GetString("DeleteOriginalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Desired file size.
        /// </summary>
        public static string DesiredFileSize {
            get {
                return ResourceManager.GetString("DesiredFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Extension list cannot be empty.
        /// </summary>
        public static string EmptyExtensionsList {
            get {
                return ResourceManager.GetString("EmptyExtensionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preset list cannot be empty.
        /// </summary>
        public static string EmptyPresetsList {
            get {
                return ResourceManager.GetString("EmptyPresetsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на File extensions:.
        /// </summary>
        public static string FileExtensions {
            get {
                return ResourceManager.GetString("FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter:.
        /// </summary>
        public static string FilterColon {
            get {
                return ResourceManager.GetString("FilterColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Filter, from 0 to 5, a higher value leads to reduced size and slower conversion speed..
        /// </summary>
        public static string FilterTooltipForPNG {
            get {
                return ResourceManager.GetString("FilterTooltipForPNG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Windows forbids using the next characters in the file path: \ / : * ? &quot;&quot; &lt; &gt; |.
        /// </summary>
        public static string ForbiddenWindowsSymbols {
            get {
                return ResourceManager.GetString("ForbiddenWindowsSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на High quality.
        /// </summary>
        public static string HighQuality {
            get {
                return ResourceManager.GetString("HighQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Hover over the setting to see a tooltip.
        /// </summary>
        public static string HoverOverTheSettingToSeeATooltip {
            get {
                return ResourceManager.GetString("HoverOverTheSettingToSeeATooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Поиск локализованного ресурса типа System.Drawing.Icon, аналогичного (Значок).
        /// </summary>
        public static System.Drawing.Icon Icon {
            get {
                object obj = ResourceManager.GetObject("Icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Invalid value.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на KiB.
        /// </summary>
        public static string KiB {
            get {
                return ResourceManager.GetString("KiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Less than 8 MiB.
        /// </summary>
        public static string LessThan8MiB {
            get {
                return ResourceManager.GetString("LessThan8MiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на lossless.
        /// </summary>
        public static string Lossless {
            get {
                return ResourceManager.GetString("Lossless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lossless.
        /// </summary>
        public static string LosslessCapital {
            get {
                return ResourceManager.GetString("LosslessCapital", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lower resolution.
        /// </summary>
        public static string LowerResolution {
            get {
                return ResourceManager.GetString("LowerResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Lower resolution if necessary.
        /// </summary>
        public static string LowerTheResolutionWhenNecessary {
            get {
                return ResourceManager.GetString("LowerTheResolutionWhenNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Shell WebP Converter.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum compression.
        /// </summary>
        public static string MaximumCompression {
            get {
                return ResourceManager.GetString("MaximumCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum compression, smallest file size.
        /// </summary>
        public static string MaximumCompressionSmallestFileSize {
            get {
                return ResourceManager.GetString("MaximumCompressionSmallestFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Maximum quality.
        /// </summary>
        public static string MaximumQuality {
            get {
                return ResourceManager.GetString("MaximumQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium compression.
        /// </summary>
        public static string MediumCompression {
            get {
                return ResourceManager.GetString("MediumCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium compression, medium file size.
        /// </summary>
        public static string MediumCompressionMediumFileSize {
            get {
                return ResourceManager.GetString("MediumCompressionMediumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Medium quality.
        /// </summary>
        public static string MediumQuality {
            get {
                return ResourceManager.GetString("MediumQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Context menu has been cleared.
        /// </summary>
        public static string MenuClearSuccess {
            get {
                return ResourceManager.GetString("MenuClearSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Context menu has been successfully updated.
        /// </summary>
        public static string MenuUpdateSuccess {
            get {
                return ResourceManager.GetString("MenuUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на MiB.
        /// </summary>
        public static string MiB {
            get {
                return ResourceManager.GetString("MiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum loss, high compression.
        /// </summary>
        public static string MinLossHighCompression {
            get {
                return ResourceManager.GetString("MinLossHighCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimum loss, medium compression.
        /// </summary>
        public static string MinLossMediumCompression {
            get {
                return ResourceManager.GetString("MinLossMediumCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Move ⇵
        ///Delete ╳.
        /// </summary>
        public static string Move_Delete {
            get {
                return ResourceManager.GetString("Move_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на The next task can be started only after the current one is completed..
        /// </summary>
        public static string NextTaskStartMustWaitCurrent {
            get {
                return ResourceManager.GetString("NextTaskStartMustWaitCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No compression.
        /// </summary>
        public static string NoCompression {
            get {
                return ResourceManager.GetString("NoCompression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на No compression, large file size.
        /// </summary>
        public static string NoCompressionLargeFileSize {
            get {
                return ResourceManager.GetString("NoCompressionLargeFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Notify when folder processing is complete.
        /// </summary>
        public static string NotifyWhenFolderProcessingEnds {
            get {
                return ResourceManager.GetString("NotifyWhenFolderProcessingEnds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Processing of &quot;{0}&quot; is completed.
        /// </summary>
        public static string ObjectProcessingCompleted {
            get {
                return ResourceManager.GetString("ObjectProcessingCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Overwrite files with the same names.
        /// </summary>
        public static string OverwriteFilesWithTheSameNames {
            get {
                return ResourceManager.GetString("OverwriteFilesWithTheSameNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PNG, smaller file size.
        /// </summary>
        public static string PNG_SmallerFileSize {
            get {
                return ResourceManager.GetString("PNG_SmallerFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на PNG, standard file size .
        /// </summary>
        public static string PNG_StandardFileSize {
            get {
                return ResourceManager.GetString("PNG_StandardFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Postfix.
        /// </summary>
        public static string Postfix {
            get {
                return ResourceManager.GetString("Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Postfix:.
        /// </summary>
        public static string PostfixColon {
            get {
                return ResourceManager.GetString("PostfixColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Postfix length shouldn&apos;t exceed 128 symbols.
        /// </summary>
        public static string PostfixLengthOver128 {
            get {
                return ResourceManager.GetString("PostfixLengthOver128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preset.
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Preset name.
        /// </summary>
        public static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Presets:.
        /// </summary>
        public static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Represents which conversion presets will be shown in the context menu. 100 — lossless, -1 — customizable quality, 85 — 85% quality, etc..
        /// </summary>
        public static string PresetsTooltip {
            get {
                return ResourceManager.GetString("PresetsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quality:.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Quality as a percentage.
        /// </summary>
        public static string QualityTooltip {
            get {
                return ResourceManager.GetString("QualityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Set of presets:.
        /// </summary>
        public static string SetOfPresets {
            get {
                return ResourceManager.GetString("SetOfPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на SSIM is the similarity level, in percent. 100 means an absolutely identical image, 95 means it differs by no more than 5%..
        /// </summary>
        public static string SSIM_Tooltip {
            get {
                return ResourceManager.GetString("SSIM_Tooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To compression N.
        /// </summary>
        public static string ToCompressionN {
            get {
                return ResourceManager.GetString("ToCompressionN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To N% quality.
        /// </summary>
        public static string ToNQuality {
            get {
                return ResourceManager.GetString("ToNQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To size N.
        /// </summary>
        public static string ToNSize {
            get {
                return ResourceManager.GetString("ToNSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на To SSIM of N.
        /// </summary>
        public static string ToSSIM_OfN {
            get {
                return ResourceManager.GetString("ToSSIM_OfN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Unsupported extension .
        /// </summary>
        public static string UnsupportedExtension {
            get {
                return ResourceManager.GetString("UnsupportedExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Update context menu.
        /// </summary>
        public static string UpdateContextMenu {
            get {
                return ResourceManager.GetString("UpdateContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Value parsing failed.
        /// </summary>
        public static string ValueParsingFailed {
            get {
                return ResourceManager.GetString("ValueParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Visually identical quality.
        /// </summary>
        public static string VisuallyIdenticalQuality {
            get {
                return ResourceManager.GetString("VisuallyIdenticalQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Wrong arguments. Use --help for help.
        /// </summary>
        public static string WrongArgumentsHelp {
            get {
                return ResourceManager.GetString("WrongArgumentsHelp", resourceCulture);
            }
        }
    }
}
