//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Shell_WebP_Converter.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Shell_WebP_Converter.Resources.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add a conversion menu entry for folders.
        /// </summary>
        public static string AddConversionEntryForFolders {
            get {
                return ResourceManager.GetString("AddConversionEntryForFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced mode.
        /// </summary>
        public static string AdvancedMode {
            get {
                return ResourceManager.GetString("AdvancedMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clear context menu.
        /// </summary>
        public static string ClearContextMenu {
            get {
                return ResourceManager.GetString("ClearContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path to the input file.
        /// </summary>
        public static string CLI_InputTooltip {
            get {
                return ResourceManager.GetString("CLI_InputTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression level:.
        /// </summary>
        public static string CompressionLevel {
            get {
                return ResourceManager.GetString("CompressionLevel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compression, from 0 to 6, a higher value leads to a reduction in size or an increase in quality at the same size, also leads to a decrease in the conversion rate.
        /// </summary>
        public static string CompressionTooltip {
            get {
                return ResourceManager.GetString("CompressionTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress to.
        /// </summary>
        public static string CompressTo {
            get {
                return ResourceManager.GetString("CompressTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compress to a specific file size.
        /// </summary>
        public static string CompressToThreshold {
            get {
                return ResourceManager.GetString("CompressToThreshold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to One or more conversion failed. See logs for details.
        /// </summary>
        public static string ConversionFail {
            get {
                return ResourceManager.GetString("ConversionFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Convert to WebP.
        /// </summary>
        public static string ConvertToWebP {
            get {
                return ResourceManager.GetString("ConvertToWebP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom conversion settings.
        /// </summary>
        public static string CustomConversionSettings {
            get {
                return ResourceManager.GetString("CustomConversionSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizable.
        /// </summary>
        public static string Customizable {
            get {
                return ResourceManager.GetString("Customizable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There can be only one preset with the &quot;customizable&quot; mode in the set.
        /// </summary>
        public static string CustomizableAlreadyExists {
            get {
                return ResourceManager.GetString("CustomizableAlreadyExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Customizable quality.
        /// </summary>
        public static string CustomizableQuality {
            get {
                return ResourceManager.GetString("CustomizableQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom settings .
        /// </summary>
        public static string CustomSettings {
            get {
                return ResourceManager.GetString("CustomSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete original.
        /// </summary>
        public static string DeleteOriginal {
            get {
                return ResourceManager.GetString("DeleteOriginal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete original file.
        /// </summary>
        public static string DeleteOriginalFile {
            get {
                return ResourceManager.GetString("DeleteOriginalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Desired file size.
        /// </summary>
        public static string DesiredFileSize {
            get {
                return ResourceManager.GetString("DesiredFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extension list cannot be empty.
        /// </summary>
        public static string EmptyExtensionsList {
            get {
                return ResourceManager.GetString("EmptyExtensionsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset list cannot be empty.
        /// </summary>
        public static string EmptyPresetsList {
            get {
                return ResourceManager.GetString("EmptyPresetsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File extensions:.
        /// </summary>
        public static string FileExtensions {
            get {
                return ResourceManager.GetString("FileExtensions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Windows forbids using the next characters in the file path: \ / : * ? &quot;&quot; &lt; &gt; |.
        /// </summary>
        public static string ForbiddenWindowsSymbols {
            get {
                return ResourceManager.GetString("ForbiddenWindowsSymbols", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid value.
        /// </summary>
        public static string InvalidValue {
            get {
                return ResourceManager.GetString("InvalidValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KiB.
        /// </summary>
        public static string KiB {
            get {
                return ResourceManager.GetString("KiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to lossless.
        /// </summary>
        public static string Lossless {
            get {
                return ResourceManager.GetString("Lossless", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower resolution.
        /// </summary>
        public static string LowerResolution {
            get {
                return ResourceManager.GetString("LowerResolution", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower resolution if necessary.
        /// </summary>
        public static string LowerTheResolutionWhenNecessary {
            get {
                return ResourceManager.GetString("LowerTheResolutionWhenNecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shell WebP Converter.
        /// </summary>
        public static string MainWindowTitle {
            get {
                return ResourceManager.GetString("MainWindowTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu has been cleared.
        /// </summary>
        public static string MenuClearSuccess {
            get {
                return ResourceManager.GetString("MenuClearSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context menu has been successfully updated.
        /// </summary>
        public static string MenuUpdateSuccess {
            get {
                return ResourceManager.GetString("MenuUpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MiB.
        /// </summary>
        public static string MiB {
            get {
                return ResourceManager.GetString("MiB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mode.
        /// </summary>
        public static string Mode {
            get {
                return ResourceManager.GetString("Mode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move ⇵
        ///Delete ╳.
        /// </summary>
        public static string Move_Delete {
            get {
                return ResourceManager.GetString("Move_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The next task can be started only after the current one is completed..
        /// </summary>
        public static string NextTaskStartMustWaitCurrent {
            get {
                return ResourceManager.GetString("NextTaskStartMustWaitCurrent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix.
        /// </summary>
        public static string Postfix {
            get {
                return ResourceManager.GetString("Postfix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix:.
        /// </summary>
        public static string PostfixColon {
            get {
                return ResourceManager.GetString("PostfixColon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Postfix length shouldn&apos;t exceed 128 symbols.
        /// </summary>
        public static string PostfixLengthOver128 {
            get {
                return ResourceManager.GetString("PostfixLengthOver128", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset.
        /// </summary>
        public static string Preset {
            get {
                return ResourceManager.GetString("Preset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preset name.
        /// </summary>
        public static string PresetName {
            get {
                return ResourceManager.GetString("PresetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Presets:.
        /// </summary>
        public static string Presets {
            get {
                return ResourceManager.GetString("Presets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Represents which conversion presets will be shown in the context menu. 100 — lossless, -1 — customizable quality, 85 — 85% quality, etc..
        /// </summary>
        public static string PresetsTooltip {
            get {
                return ResourceManager.GetString("PresetsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality:.
        /// </summary>
        public static string Quality {
            get {
                return ResourceManager.GetString("Quality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quality as a percentage.
        /// </summary>
        public static string QualityTooltip {
            get {
                return ResourceManager.GetString("QualityTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set of presets:.
        /// </summary>
        public static string SetOfPresets {
            get {
                return ResourceManager.GetString("SetOfPresets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string Settings {
            get {
                return ResourceManager.GetString("Settings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To N% quality.
        /// </summary>
        public static string ToNQuality {
            get {
                return ResourceManager.GetString("ToNQuality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To N size.
        /// </summary>
        public static string ToNSize {
            get {
                return ResourceManager.GetString("ToNSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsupported extension .
        /// </summary>
        public static string UnsupportedExtension {
            get {
                return ResourceManager.GetString("UnsupportedExtension", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update context menu.
        /// </summary>
        public static string UpdateContextMenu {
            get {
                return ResourceManager.GetString("UpdateContextMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value parsing failed.
        /// </summary>
        public static string ValueParsingFailed {
            get {
                return ResourceManager.GetString("ValueParsingFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong arguments. Use --help for help.
        /// </summary>
        public static string WrongArgumentsHelp {
            get {
                return ResourceManager.GetString("WrongArgumentsHelp", resourceCulture);
            }
        }
    }
}
